# Generated by Django 5.1.2 on 2024-11-01 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('example', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1_entries', to='dictionary.dictionaryentry')),
                ('word2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2_entries', to='dictionary.dictionaryentry')),
            ],
            options={
                'unique_together': {('word1', 'word2')},
            },
        ),
    ]
