# Generated by Django 5.1.2 on 2024-11-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='example',
        ),
    ]
