# Generated by Django 5.1.2 on 2024-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0002_remove_dictionaryentry_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creator', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/images/')),
                ('language_combination', models.CharField(max_length=50)),
                ('combinations', models.ManyToManyField(blank=True, related_name='collections', to='dictionary.wordcombination')),
            ],
        ),
    ]
