# Generated by Django 5.1.2 on 2024-11-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='combinations',
            new_name='word_combinations',
        ),
    ]
