# Generated by Django 5.1.2 on 2024-11-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_delete_emptymodel_collectioncombinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionCombinations',
        ),
        migrations.CreateModel(
            name='CollectionCombination',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('collection.collection',),
        ),
    ]
